// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package health

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson57fbf2e6DecodeGithubComDotmeshIoDsDeployerPkgHealth(in *jlexer.Lexer, out *HealthResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "health":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				if !in.IsDelim('}') {
					out.Health = make(map[string]bool)
				} else {
					out.Health = nil
				}
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v1 bool
					v1 = bool(in.Bool())
					(out.Health)[key] = v1
					in.WantComma()
				}
				in.Delim('}')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson57fbf2e6EncodeGithubComDotmeshIoDsDeployerPkgHealth(out *jwriter.Writer, in HealthResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"health\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if in.Health == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v2First := true
			for v2Name, v2Value := range in.Health {
				if v2First {
					v2First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v2Name))
				out.RawByte(':')
				out.Bool(bool(v2Value))
			}
			out.RawByte('}')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v HealthResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson57fbf2e6EncodeGithubComDotmeshIoDsDeployerPkgHealth(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v HealthResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson57fbf2e6EncodeGithubComDotmeshIoDsDeployerPkgHealth(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *HealthResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson57fbf2e6DecodeGithubComDotmeshIoDsDeployerPkgHealth(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *HealthResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson57fbf2e6DecodeGithubComDotmeshIoDsDeployerPkgHealth(l, v)
}
